import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import styled from 'styled-components';

const Title = styled.h1`
  color: green;
  text-decoration: underline;
  font-family: ${({ theme }) => theme.font.antonio};
`;

const Paragraph = styled.p`
  color: lightcoral;
  font-size: 1.15rem;
  font-family: ${({ theme }) => theme.font.spartan};
`;

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Title className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </Title>

        <Paragraph className={styles.description}>
          Get started by editing <code className={styles.code}>pages/index.js</code>
        </Paragraph>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <Paragraph>Find in-depth information about Next.js features and API.</Paragraph>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <Paragraph>Learn about Next.js in an interactive course with quizzes!</Paragraph>
          </a>

          <a href="https://github.com/vercel/next.js/tree/master/examples" className={styles.card}>
            <h2>Examples &rarr;</h2>
            <Paragraph>Discover and deploy boilerplate example Next.js projects.</Paragraph>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <Paragraph>Instantly deploy your Next.js site to a public URL with Vercel.</Paragraph>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
